# Generated by Django 4.2.30 on 2026-05-10 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueShareToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('issue_id', models.UUIDField(db_index=True)),
                ('project_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('allowed_emails', models.JSONField(blank=True, default=list)),
                ('allow_comments', models.BooleanField(default=False)),
                ('allow_attachments', models.BooleanField(default=False)),
                ('allow_approval', models.BooleanField(default=False)),
                ('show_assignees', models.BooleanField(default=True)),
                ('show_internal_comments', models.BooleanField(default=False)),
                ('show_activity', models.BooleanField(default=False)),
                ('show_custom_fields', models.BooleanField(default=True)),
                ('custom_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_share_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_issue_tokens',
            },
        ),
        migrations.CreateModel(
            name='SharedIssueExternalComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_name', models.CharField(max_length=255)),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('comment_html', models.TextField()),
                ('is_approval_response', models.BooleanField(default=False)),
                ('approval_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_comments', to='shared_issues.issuesharetoken')),
            ],
            options={
                'db_table': 'shared_issue_external_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedIssueAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('actor_name', models.CharField(blank=True, default='', max_length=255)),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('action', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='shared_issues.issuesharetoken')),
            ],
            options={
                'db_table': 'shared_issue_access_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['share_token', 'created_at'], name='shared_issu_share_t_cb92e1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='issuesharetoken',
            index=models.Index(fields=['token', 'is_active'], name='shared_issu_token_1d4e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='issuesharetoken',
            index=models.Index(fields=['issue_id', 'is_active'], name='shared_issu_issue_i_afdc8e_idx'),
        ),
    ]
